#1 PONERLE UN NOMBRE
name: "FLUJO DE TRABAJAO 1"
#darle un evento para q se ejecute el flujo de trabajo
on: [push]

jobs:
 prueba1:
  runs-on: ubuntu-latest
  steps:
   - name: Mensaje
     run: echo "Hola Mundo"
   - name: Crea Archivo
     run: touch alumnos.txt
   - name: Adiciona Alumnos
     run: echo "Juan" >> alumnos.txt
     run: echo "Pedro" >> alumnos.txt
   - name: Muestra Archivo
     run: cat alumnos.txt