#1 PONERLE UN NOMBRE
name: "FLUJO DE TRABAJAO 1"
#darle un evento para q se ejecute el flujo de trabajo
on: [push]

jobs:
 prueba1:
  runs-on: ubuntu-latest
  steps:
   - name: Mensaje
     run: echo "Hola Mundo"
   - name: Mensaje2
     run: echo "Segunda iteracci贸n con Git Actions"
   - name: Mensaje3
     run: echo "Tercera iteracci贸n con Git Actions"
   - name: Mensaje4
     run: echo "Cuarta iteracci贸n con Git Actions"
   - name: Mensaje5 
     run: echo "Quinta iteracci贸n con Git Actions"